---
editor:
  render-on-save: true
---

### Windows

We need to look at the `pyenv-win` project to install `pyenv` for windows.
You can find the link to the project here:

[https://github.com/pyenv-win/pyenv-win](https://github.com/pyenv-win/pyenv-win)


There are a few methods of installing `pyenv-win` on Windows.

1. Using the Windows PowerShell
2. Manual installation from `zip`
3. Using a windows package manager (e.g., chocolatey, scoop)

#### Method 1: Windows Powershell

You can run the following command in the PowerShell terminal:

```powershell
Invoke-WebRequest -UseBasicParsing -Uri "https://raw.githubusercontent.com/pyenv-win/pyenv-win/master/pyenv-win/install-pyenv-win.ps1" -OutFile "./install-pyenv-win.ps1"; &"./install-pyenv-win.ps1"
```

If you see an `UnauthorizedAccess` error you need to:

1. Open Windows PowerShell with the "Run as administer" option
2. Run the following command:

```powershell
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine
```

If you are getting a "not digitally signed" error, you may also need to unblock
the `pyenv` script:

```powershell
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine
Unblock-File (Join-Path $env:PYENV 'bin/pyenv.ps1')


```

#### Method 2: Manual installation

1. Download [pyenv-win.zip](https://github.com/pyenv-win/pyenv-win/archive/master.zip)

2. Create a `.pyenv` folder in your home directory. In PowerShell or Git Bash:

```sh
mkdir $HOME/.pyenv
```

3. Extract the `pyenv-win.zip` contents into the newly created `.pyenv` directory you just created

4. You should have a a `bin/` directory in `$HOME/.pyenv/pyenv-win/bin`

#### Method 3: Package Managers

You can install `pyenv-win` using one of the Windows Package managers:

1. Chocolatey: [https://chocolatey.org/install](https://chocolatey.org/install)
2. Scoop: [https://scoop.sh/](https://scoop.sh/)

At the time of writing, `pyenv-win` is not in the
[`winget`](https://learn.microsoft.com/en-us/windows/package-manager/winget/#install-winget)
repositories

Chocolatey

```powershell
choco install pyenv-win
```

Scoop

```powershell
scoop bucket add main
scoop install main/pyenv
```

#### Post installation setup

You need to add a few variables into your Environment Variables.
You can do this by pressing the windows key and searching for the "Edit environment variables for your account".
Or you can run the commands in PowerShell to add them.

In general you need to add 3 `pyenv` variables and append a directory to the `Path`.
The `PYENV`, `PYENV_HOME`, and `PYENV_ROOT` user variables need to all point to your `pyenv-win` directory
within your `.pyenv` folder in your home directory.

```powershell
[System.Environment]::SetEnvironmentVariable('PYENV',$env:USERPROFILE + "\.pyenv\pyenv-win\","User")
[System.Environment]::SetEnvironmentVariable('PYENV_ROOT',$env:USERPROFILE + "\.pyenv\pyenv-win\","User")
[System.Environment]::SetEnvironmentVariable('PYENV_HOME',$env:USERPROFILE + "\.pyenv\pyenv-win\","User")
```

The `.pyenv\pyenv-win\bin\` directory also needs to be added to the beginning of the `Path` variable

```powershell
[System.Environment]::SetEnvironmentVariable('path', $env:USERPROFILE + "\.pyenv\pyenv-win\bin;" + $env:USERPROFILE + "\.pyenv\pyenv-win\shims;" + [System.Environment]::GetEnvironmentVariable('path', "User"),"User")
```

#### Confirm installation

You can confirm your installation with:

```sh
pyenv --version
```

You should not be seeing any "command not found" errors.
Opening things in a new terminal or restarting applications may help.
